version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT}:5000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - .env  # This loads the .env file's variables into the environment

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    env_file:
      - .env  # Same for the frontend service

networks:
  default:
    external:
      name: my-network
